# -*- coding: utf-8 -*-
"""Bootcamp Ciência de Dados - Unimed BH

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/142xg6hPmMDItWPNahNvFCR3apETsW3vC

Introdução a biblioteca Pandas
"""

import pandas as pd

from pandas.io.parsers.readers import read_csv
df = read_csv("/content/drive/MyDrive/Bootcamp Unimed/Gapminder.csv", ";")

df.head

df=df.rename(columns={"country":"País", "continent":"Contintente", "year":"Ano", "lifeExp":"Expectativa de Vida", "pop":"População Total", "gdpPercap":"Pib"})

df=df.rename(columns={"country":"País", "Contintente":"Continente", "year":"Ano", "lifeExp":"Expectativa de Vida", "pop":"População Total", "gdpPercap":"Pib"})

df.head(5)

df.shape

df.dtypes

df.tail()

df.describe()

df["País"].unique()

Bhutan = df.loc[df["País"]=="Bhutan"]

Bhutan.head(10)

df.groupby("Continente")["País"].nunique()

df.groupby("Ano")["Expectativa de Vida"].mean()

df.groupby("Continente")["Expectativa de Vida"].max()

df.groupby("Pib")["Expectativa de Vida"].max()

df["Pib"].mean()

"""Trabalhando com planilhas no Excel"""

df1=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Aracaju.xlsx")
df2=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Fortaleza.xlsx")
df3=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Natal.xlsx")
df4=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Recife.xlsx")
df5=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Salvador.xlsx")

df1.head

df2.head

df3.head

df4.head

df5.head

df_excel=df=pd.concat([df1,df2,df3,df4,df5])

df_excel.sample(10)

df_excel.dtypes

df_excel["Data"] = df["Data"].astype("int64")

df.dtypes

df_excel["Data"] = df["Data"].astype("datetime64[ns]")

df_excel["LojaID"] = df["LojaID"].astype("object")

df.dtypes

df_excel.isnull().sum()

df_excel.isnull()

df_excel["Vendas"].fillna(0, inplace=True)

df_excel["Receita"] = df["Vendas"].mul(df["Qtde"])

df_excel.sample(10)

df_excel["Receita/Vendas"] = df["Receita"]/df["Vendas"]

df_excel.head

df_excel["Receita"].max()

df_excel["Receita"].min()

df_excel.groupby("LojaID")["Receita"].min()

df_excel.nlargest(5, "Receita")

df_excel.nsmallest(5, "Receita")

df_excel.groupby("Cidade")["Receita"].sum()

df_excel.sort_values("Receita", ascending=False).head(10)

"""Trabalhando com Datas no Pandas"""

df_excel.dtypes

df_excel["Data"] = df["Data"].astype("int64")

df_excel.dtypes

df_excel["Data"] = pd.to_datetime(df_excel["Data"])

df_excel.dtypes

df_excel.groupby(df["Data"].dt.year)["Receita"].sum()

df_excel["Venda por ano"] = df_excel["Data"].dt.year

df_excel["Venda por mês"], df_excel["Venda por dia"] = (df_excel["Data"].dt.month, df_excel["Data"].dt.day)

df_excel.head(5)

df_excel["Data"].min

df_excel["Diferença_dias"] = df_excel["Data"].min()

df_excel["Trimestre_venda"] = df["Data"].dt.quarter

df_excel.sample(10)

vendas_marco_19 = df_excel.loc[(df_excel["Data"].dt.year==2019)&(df["Data"].dt.month==3)]

vendas_marco_19.sample(20)

"""Visualização de dados"""

df_excel["LojaID"].value_counts(ascending=True)

df_excel["LojaID"].value_counts(ascending=True).plot.barh();
plt.savefig("gráfico de barras horizontal LojaID.png")

df_excel["LojaID"].value_counts().plot.bar();

df_excel.head

df_excel.groupby(df_excel["Data"].dt.year)["Receita"].sum().plot.pie();
plt.savefig("gráfico pizza Receita X Ano.png")

df_excel["Cidade"].value_counts()

import matplotlib.pyplot as plt
df_excel["Cidade"].value_counts().plot.bar(title ="Total de vendas por cidade", color="purple")
plt.xlabel("Cidade")
plt.ylabel("Total de vendas");
plt.savefig("gráfico de coluna Total de vendas por cidade.png")

plt.style.use("ggplot")

df_excel.groupby(df_excel["Venda por mês"])["Qtde"].sum().plot(title="Produtos vendidos x mês", color="purple")
plt.xlabel("Mês")
plt.ylabel("Total de produtos vendidos")
plt.legend();



df_excel_2019 = df_excel[df_excel["Venda por ano"] == 2019]

df_excel_2019.groupby(df_excel_2019["Venda por mês"])["Qtde"].sum().plot(marker = "*", color="purple")
plt.xlabel("Mês")
plt.ylabel("Total de Produtos Vendidos")
plt.legend()
plt.savefig("gráfico de linha QTDE X MÊS.png")

plt.hist(df_excel["Qtde"], color="purple");
plt.savefig("gráfico QTDE.png")

plt.scatter(x=df_excel_2019["Venda por dia"], y=df_excel_2019["Receita"], color="purple");
plt.title("Receita x Venda por dia")
plt.savefig("gráfico de dispersão Receita X Venda por dia.png")

df_excel_2019.groupby(df_excel_2019["Venda por mês"])["Qtde"].sum().plot(marker="v", color="purple")
plt.title("Quantidade de produtos vendidos x mês")
plt.xlabel("Mês")
plt.ylabel("Total de produtos vendidos");
plt.legend();
plt.savefig("gráfico QTDE X MÊS.png")

"""Análise exploratória

Nesta aula usamos uma base de dados fornecida pela Microsoft, importamos bibliotecas Matplotlib e Pandas

---
"""

import pandas as pd

import matplotlib.pyplot as plt
plt.style.use("seaborn")

from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")

df.head()

df.shape

df["Valor Venda"].sum()

df["Custo"]= df["Custo Unitário"].mul(df["Quantidade"])

df.head(1)

round(df["Custo"].sum(),2)

df["Lucro"] = df["Valor Venda"] - df["Custo"]

round(df["Lucro"].sum(),2)

df["Tempo_envio"] = df["Data Envio"] - df["Data Venda"]

df["Tempo envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df["Tempo_envio"].dtype

df.groupby("Marca")["Tempo_envio"].mean()

df.describe()

df.isnull().sum()

df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

"""No código acima, recebemos o resultado em notação científica, o próximo código irá retornar o valor completo."""

pd.options.display.float_format = '{:2,.2f}'.format

lucro_ano=df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index
lucro_ano()

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total de Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produtos");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum()

df_2009=df[df["Data Venda"].dt.year==2009]

df_2009.head()

df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title="Lucro x Mês")
plt.xlabel("Lucro")
plt.ylabel("Mes");

df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title="Lucro x Venda")
plt.xlabel("Marca")
plt.ylabel("Lucro")
plt.xticks(rotation="horizontal");

df_2009.groupby("Classe")["Lucro"].sum().plot.bar(title="Classe x Lucro")
plt.xlabel("Classe")
plt.ylabel("Lucro")
plt.xticks(rotation="horizontal")
plt.savefig("gráfico colunas vert Classes x Lucro")

df["Tempo_envio"].describe()

plt.boxplot(df["Tempo envio"])
plt.savefig("gráfico boxplot Tempo envio")

plt.hist(df["Tempo envio"])
plt.savefig("gráfico histograma Tempo envio")

df["Tempo_envio"].min()

df["Tempo_envio"].max()

df[df["Tempo envio"]==20]

df.to_csv("df_vendas_novo.csv", index=False)