# -*- coding: utf-8 -*-
"""Bootcamp Ciência de Dados - Unimed BH

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/142xg6hPmMDItWPNahNvFCR3apETsW3vC

Introdução a biblioteca Pandas
"""

import pandas as pd

from pandas.io.parsers.readers import read_csv
df = read_csv("/content/drive/MyDrive/Bootcamp Unimed/Gapminder.csv", ";")

df.head

df=df.rename(columns={"country":"País", "continent":"Contintente", "year":"Ano", "lifeExp":"Expectativa de Vida", "pop":"População Total", "gdpPercap":"Pib"})

df=df.rename(columns={"country":"País", "Contintente":"Continente", "year":"Ano", "lifeExp":"Expectativa de Vida", "pop":"População Total", "gdpPercap":"Pib"})

df.head(5)

df.shape

df.dtypes

df.tail()

df.describe()

df["País"].unique()

Bhutan = df.loc[df["País"]=="Bhutan"]

Bhutan.head(10)

df.groupby("Continente")["País"].nunique()

df.groupby("Ano")["Expectativa de Vida"].mean()

df.groupby("Continente")["Expectativa de Vida"].max()

df.groupby("Pib")["Expectativa de Vida"].max()

df["Pib"].mean()

"""Trabalhando com planilhas no Excel"""

df1=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Aracaju.xlsx")
df2=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Fortaleza.xlsx")
df3=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Natal.xlsx")
df4=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Recife.xlsx")
df5=pd.read_excel("/content/drive/MyDrive/Bootcamp Unimed/datasets/Salvador.xlsx")

df1.head

df2.head

df3.head

df4.head

df5.head

df_excel=df=pd.concat([df1,df2,df3,df4,df5])

df_excel.sample(10)

df_excel.dtypes

df_excel["Data"] = df["Data"].astype("int64")

df.dtypes

df_excel["Data"] = df["Data"].astype("datetime64[ns]")

df_excel["LojaID"] = df["LojaID"].astype("object")

df.dtypes

df_excel.isnull().sum()

df_excel.isnull()

df_excel["Vendas"].fillna(0, inplace=True)

df_excel["Receita"] = df["Vendas"].mul(df["Qtde"])

df_excel.sample(10)

df_excel["Receita/Vendas"] = df["Receita"]/df["Vendas"]

df_excel.head

df_excel["Receita"].max()

df_excel["Receita"].min()

df_excel.groupby("LojaID")["Receita"].min()

df_excel.nlargest(5, "Receita")

df_excel.nsmallest(5, "Receita")

df_excel.groupby("Cidade")["Receita"].sum()

df_excel.sort_values("Receita", ascending=False).head(10)

"""Trabalhando com Datas no Pandas"""

df_excel.dtypes

df_excel["Data"] = df["Data"].astype("int64")

df_excel.dtypes

df_excel["Data"] = pd.to_datetime(df_excel["Data"])

df_excel.dtypes

df_excel.groupby(df["Data"].dt.year)["Receita"].sum()

df_excel["Venda por ano"] = df_excel["Data"].dt.year

df_excel["Venda por mês"], df_excel["Venda por dia"] = (df_excel["Data"].dt.month, df_excel["Data"].dt.day)

df_excel.head(5)

df_excel["Data"].min

df_excel["Diferença_dias"] = df_excel["Data"].min()

df_excel["Trimestre_venda"] = df["Data"].dt.quarter

df_excel.sample(10)

vendas_marco_19 = df_excel.loc[(df_excel["Data"].dt.year==2019)&(df["Data"].dt.month==3)]

vendas_marco_19.sample(20)

"""Visualização de dados"""

df_excel["LojaID"].value_counts(ascending=True)

df_excel=df=pd.concat([df1,df2,df3,df4,df5])

"""Análise exploratória"""